import { useState } from "react";
import { motion } from "framer-motion";
import { Shield, FileText, Scale, BarChart3, AlertTriangle, Copy, Download, RefreshCw, Code2, UserCheck, ArrowRight, FileSpreadsheet, Presentation } from "lucide-react";
import { RiskBadge, ConfidenceBadge } from "./RiskBadge";
import { Button } from "@/components/ui/button";
import ReactMarkdown from "react-markdown";
import { toast } from "sonner";
import { exportAssessmentToExcel } from "@/lib/export-excel";
import { exportAssessmentToPptx } from "@/lib/export-pptx";

export interface AssessmentData {
  summary: string;
  riskTier: "unacceptable" | "high" | "limited" | "minimal" | "not_ai" | "needs_clarification" | "unknown";
  justification: string;
  confidence: "high" | "medium" | "low";
  assumptions: string;
  role?: string;
  nextSteps?: string;
}

interface Props {
  data: AssessmentData;
  rawResponse?: string;
  latencyMs?: number;
  onRefine?: () => void;
  devMode?: boolean;
  userQuery?: string;
}

function Section({
  icon: Icon,
  title,
  children,
  delay = 0,
}: {
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
  delay?: number;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, delay }}
      className="rounded-xl border border-border bg-card p-5"
    >
      <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-foreground">
        <Icon className="h-4 w-4 text-primary" />
        {title}
      </div>
      <div className="text-sm leading-relaxed text-card-foreground/80 prose prose-sm max-w-none">
        {children}
      </div>
    </motion.div>
  );
}

function formatAssessmentText(data: AssessmentData): string {
  let text = `EU AI Act Risk Assessment
========================

AI System Summary:
${data.summary}

Risk Classification: ${data.riskTier.toUpperCase()}
`;
  if (data.role && data.role !== "unknown") {
    text += `\nYour Role: ${data.role.toUpperCase()}\n`;
  }
  text += `
Justification:
${data.justification}

Confidence Level: ${data.confidence.toUpperCase()}

Assumptions & Missing Information:
${data.assumptions}
`;
  if (data.nextSteps) {
    text += `\nRecommended Next Steps:\n${data.nextSteps}\n`;
  }
  text += `
---
Generated by AI ACT Buddy (aiactbuddy.com)
`;
  return text;
}

export function AssessmentCard({ data, rawResponse, latencyMs, onRefine, devMode, userQuery }: Props) {
  const [showRaw, setShowRaw] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(formatAssessmentText(data));
    toast.success("Assessment copied to clipboard");
  };

  const handleExport = () => {
    const text = formatAssessmentText(data);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `eu-ai-act-assessment-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Assessment exported");
  };

  return (
    <div className="space-y-3 w-full max-w-3xl mx-auto">
      <Section icon={FileText} title="AI System Summary" delay={0}>
        <ReactMarkdown>{data.summary}</ReactMarkdown>
      </Section>

      <Section icon={Shield} title="Risk Classification" delay={0.08}>
        <div className="flex items-center gap-3">
          <RiskBadge tier={data.riskTier} />
        </div>
      </Section>

      <Section icon={Scale} title="Justification" delay={0.16}>
        <ReactMarkdown>{data.justification}</ReactMarkdown>
      </Section>

      {data.role && data.role !== "unknown" && (
        <Section icon={UserCheck} title="Your Role Under the AI Act" delay={0.24}>
          <span className="inline-flex items-center rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary capitalize">
            {data.role}
          </span>
        </Section>
      )}

      <Section icon={BarChart3} title="Confidence Level" delay={0.28}>
        <div className="flex items-center gap-3">
          <ConfidenceBadge level={data.confidence} />
        </div>
      </Section>

      <Section icon={AlertTriangle} title="Assumptions & Missing Information" delay={0.32}>
        <ReactMarkdown>{data.assumptions}</ReactMarkdown>
      </Section>

      {data.nextSteps && (
        <Section icon={ArrowRight} title="Recommended Next Steps" delay={0.36}>
          <ReactMarkdown>{data.nextSteps}</ReactMarkdown>
        </Section>
      )}

      {/* Action bar */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="flex flex-wrap items-center gap-2 pt-1"
      >
        <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5 text-xs">
          <Copy className="h-3.5 w-3.5" />
          Copy
        </Button>
        <Button variant="outline" size="sm" onClick={handleExport} className="gap-1.5 text-xs">
          <Download className="h-3.5 w-3.5" />
          TXT
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            exportAssessmentToExcel(data, userQuery);
            toast.success("Excel report downloaded");
          }}
          className="gap-1.5 text-xs"
        >
          <FileSpreadsheet className="h-3.5 w-3.5" />
          Excel
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            exportAssessmentToPptx(data, userQuery);
            toast.success("PowerPoint deck downloaded");
          }}
          className="gap-1.5 text-xs"
        >
          <Presentation className="h-3.5 w-3.5" />
          PPTX
        </Button>
        {onRefine && (
          <Button variant="outline" size="sm" onClick={onRefine} className="gap-1.5 text-xs">
            <RefreshCw className="h-3.5 w-3.5" />
            Refine
          </Button>
        )}
        {devMode && rawResponse && (
          <Button variant="ghost" size="sm" onClick={() => setShowRaw(!showRaw)} className="gap-1.5 text-xs ml-auto text-muted-foreground">
            <Code2 className="h-3.5 w-3.5" />
            {showRaw ? "Hide" : "Raw"}
            {latencyMs != null && <span className="text-[10px] opacity-60">{latencyMs}ms</span>}
          </Button>
        )}
      </motion.div>

      {/* Dev mode raw response */}
      {devMode && showRaw && rawResponse && (
        <motion.pre
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: "auto" }}
          className="overflow-auto rounded-lg border border-border bg-surface-sunken p-4 text-xs font-mono text-muted-foreground max-h-64"
        >
          {rawResponse}
        </motion.pre>
      )}
    </div>
  );
}
